version: 2

models:
  - name: stg_transactions
    columns:
      - name: txn_id
        tests:
          - unique
          - not_null
      - name: amount
        tests:
          - not_null

  - name: stg_decisions
    columns:
      - name: txn_id
        tests:
          - unique
          - not_null
      - name: riskflow_decision
        tests:
          - accepted_values:
              arguments:
                values: ['approve', 'decline']
      - name: naive_decision
        tests:
          - accepted_values:
              arguments:
                values: ['approve', 'decline']
